// WARNING: DO NOT EDIT. This file is Auto-Generated by AWS Mobile Hub. It will be overwritten.

// Copyright 2017-2018 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to
// copy, distribute and modify it.

// AWS Mobile Hub Project Constants
const awsmobile = {
    'aws_app_analytics': 'enable',
    'aws_cognito_identity_pool_id': 'us-east-1:7ce48bc2-1c09-4bf8-806e-28b9be7ec5a4',
    'aws_cognito_region': 'us-east-1',
    'aws_mobile_analytics_app_id': '53cbb7fa66d2447e9b09dd43f8bbe60e',
    'aws_mobile_analytics_app_region': 'us-east-1',
    'aws_project_id': 'b2f22a74-37fa-48a1-b242-ed3ff88ccb2f',
    'aws_project_name': 'spent grains',
    'aws_project_region': 'us-east-1',
    'aws_resource_name_prefix': 'spentgrains-mobilehub-916790609',
}

export default awsmobile;
